### ISSUE TITLE
mac 启动不了

### ISSUE THREAD

**Issue by shinegod** [BeichenDream/Godzilla#10]
[*] Time:2020-10-19 21:13:08 ThreadId:1 Message: load pluginJar success! pluginJarNum:0 LoadPluginJarSuccessNum:0
[*] Time:2020-10-19 21:13:08 ThreadId:1 Message: load payload success! payloadMaxNum:3 onceLoadPayloadNum:3
[*] Time:2020-10-19 21:13:09 ThreadId:1 Message: load cryption success! cryptionMaxNum:6 onceLoadCryptionNum:6
[*] Time:2020-10-19 21:13:09 ThreadId:1 Message: load plugin success! pluginMaxNum:20 onceLoadPluginNum:20
[!] Time:2020-10-19 21:13:09 ThreadId:1 Message:https://gitee.com/beichendram/Godzilla/raw/master/qqGroup.png stackTrace: java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1928)->java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)->java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)->util.functions.httpReqest(functions.java:265)->core.ApplicationConfig.invoke(ApplicationConfig.java:77)->core.ui.MainActivity.<init>(MainActivity.java:60)->core.ui.MainActivity.main(MainActivity.java:277)
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:108)
	at core.ApplicationConfig.invoke(ApplicationConfig.java:77)
	at core.ui.MainActivity.<init>(MainActivity.java:60)
	at core.ui.MainActivity.main(MainActivity.java:277)

**Comment by BeichenDream** [comment]
重新打开即可

**Comment by solomanhl** [comment]
windows也启动不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BeichenDream/Godzilla"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 晚上9:19
收件人:&nbsp;"BeichenDream/Godzilla"<Godzilla@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [BeichenDream/Godzilla] mac 启动不了 (#10)





 
重新打开即可

**Comment by BeichenDream** [comment]
> windows也启动不了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BeichenDream/Godzilla" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月19日(星期一) 晚上9:19 收件人:&nbsp;"BeichenDream/Godzilla"<Godzilla@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [BeichenDream/Godzilla] mac 启动不了 (#10) 重新打开即可 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请尝试重启重试
