### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by pascalcaron** [BeichenDream/Godzilla#11]
Please provide english translations

**Comment by BeichenDream** [comment]
> 请提供英文翻译

If the supported options are greater than the unsupported options, and the supported number is greater than 100, I will release i18n from Godzilla

Voting ends at 18:30 on 2020-11-20

https://github.com/BeichenDream/Godzilla/issues/12

**Comment by pascalcaron** [comment]
@BeichenDream any updates?

**Comment by BeichenDream** [comment]
About a month or two because I'm writing other features and time is probably tight

**Comment by pascalcaron** [comment]
> About a month or two because I'm writing other features and time is probably tight

Ok, understandable..

But if you need any help, I can help for this work? Internationalization

**Comment by BeichenDream** [comment]
I do need your help please send an email to beichendream@gmail.com

**Comment by pascalcaron** [comment]
> I do need your help please send an email to [beichendream@gmail.com](mailto:beichendream@gmail.com)

Sent email

**Comment by pascalcaron** [comment]
Any updates?

**Comment by pascalcaron** [comment]
Any updates?

**Comment by BeichenDream** [comment]
> Any updates?

This month

**Comment by b4sh1t1** [comment]
how to display english version ?

**Comment by davisaqueen** [comment]
did you success to publish with english version?

**Comment by BeichenDream** [comment]
English translation has been completed and is expected to be released in November/December

**Comment by BeichenDream** [comment]
Do any of you have an account for DeepL translation I think DeepL translation is more accurate but DeepL Pro is not allowed to be ordered in China If you have an account for DeepL you can send it to beichendream@gmail.com If no one has an account for DeepL translation it might delay the release date of the English version/i18n

**Comment by pascalcaron** [comment]
> DeepL



> Do any of you have an account for DeepL translation I think DeepL translation is more accurate but DeepL Pro is not allowed to be ordered in China If you have an account for DeepL you can send it to [beichendream@gmail.com](mailto:beichendream@gmail.com) If no one has an account for DeepL translation it might delay the release date of the English version/i18n

I have free account of DeepL. Will it help you?

**Comment by BeichenDream** [comment]
> > DeepL
> 
> > Do any of you have an account for DeepL translation I think DeepL translation is more accurate but DeepL Pro is not allowed to be ordered in China If you have an account for DeepL you can send it to [beichendream@gmail.com](mailto:beichendream@gmail.com) If no one has an account for DeepL translation it might delay the release date of the English version/i18n
> 
> I have free account of DeepL. Will it help you?

deepl free account does not seem to work with the API

**Comment by BeichenDream** [comment]
English support is now added

**Comment by BeichenDream** [comment]
English support is now added

**Comment by pascalcaron** [comment]
On which version?

**Comment by BeichenDream** [comment]
> On which version?

v4.0.1

Please use a non-Chinese operating system or change it in the configuration

![image](https://user-images.githubusercontent.com/43266206/143038295-e208f8a9-7ea7-40f4-9ff7-4a2a87d10947.png)
