### ISSUE TITLE
无法直接把url粘贴到Godzilla的框中 ，每次都要手动输入

### ISSUE THREAD

**Issue by pangyu360es** [BeichenDream/Godzilla#19]

**Comment by BeichenDream** [comment]
请留下您的联系方式 远程协助

**Comment by ClassBluer** [comment]
MAC表示也一样，同时当网址无法联通时或者文件不存在，进行测试连接操作Godzilla会崩溃，只能强制退出。

**Comment by Lhaihai** [comment]
Mac下，使用java 1.8.0_271
V1.10 可以粘贴
V2.9.2和V2.9.6不能粘贴
Mac下，使用java 11.0.9
V1.10、V2.9.2和V2.9.6都可以粘贴
解决方案：使用java 11打开

**Comment by piaolin** [comment]
Mac不是用Command键，是使用control，这点和windows使用习惯相同，但和mac使用习惯相反。
