### ISSUE TITLE
护网的时候放出来，不会是是社工吧

### ISSUE THREAD

**Issue by HToTH** [BeichenDream/Godzilla#2]

**Comment by taomujian** [comment]
滴滴，主机上线

**Comment by xxsmile123** [comment]
各大厂商盯着呢

**Comment by ki9mu** [comment]
规则写不完了

**Comment by BloodPupil** [comment]
刚从冰蝎3过来。。

**Comment by solomanhl** [comment]
下载后是扫码进群  并且满了？发自我的华为手机-------- 原始邮件 --------发件人： Blood_Pupil <notifications@github.com>日期： 2020年8月18日周二 晚上7:05收件人： BeichenDream/Godzilla <Godzilla@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [BeichenDream/Godzilla] 护网的时候放出来，不会是是社工吧 (#2)

刚从冰蝎3过来。。

**Comment by tammypi** [comment]
为啥感觉没有冰蝎3火？这种加密webshell，只能用机器学习来检测了。

**Comment by BeichenDream** [comment]
> 为啥感觉没有冰蝎3火？这种加密webshel​​l，只能用机器学习来检测了。

刚发布第二天,暂时在使用量上低于冰蝎,毕竟冰蝎是多年的项目了

**Comment by BeichenDream** [comment]
> 护网的时候放出来，不会是是社工吧
本来是准备7月份发布的,由于懒癌晚期所以拖到现在

**Comment by laohuan12138** [comment]
丢到沙箱里跑了一下，非常危险

**Comment by BeichenDream** [comment]
> 丢到沙箱里跑了一下，非常危险

以zip
