### ISSUE TITLE
命令执行窗口，无法切换目录

### ISSUE THREAD

**Issue by prship** [BeichenDream/Godzilla#22]
博主您好，跟您反馈一个功能缺陷，哥斯拉的命令执行窗口，貌似不能切换目录，执行切换目录命令后，仍然返回默认目录
![image](https://user-images.githubusercontent.com/68674231/107473599-ea55c000-6bab-11eb-9a0d-6366b84eecbf.png)
对比之下，蚁剑则可以正常处理
![image](https://user-images.githubusercontent.com/68674231/107473756-27ba4d80-6bac-11eb-861f-186cc9e08c37.png)

**Comment by BeichenDream** [comment]
- [ 添加命令行切换目录]

**Comment by BeichenDream** [comment]
- [ ] 命令行切换目录

**Comment by BeichenDream** [comment]
已修复
