### ISSUE TITLE
师傅你好，添加目标的窗口太小了不知道咋回事，之前v2的时候也是这样

### ISSUE THREAD

**Issue by YOunGWebER** [BeichenDream/Godzilla#29]
![image](https://user-images.githubusercontent.com/49063068/115322974-bd301a00-a1b9-11eb-919a-e30d9fdb6ea8.png)

**Comment by BeichenDream** [comment]
把窗口拉长还是这样吗？

**Comment by YOunGWebER** [comment]
是的
![image](https://user-images.githubusercontent.com/49063068/115330224-3897c880-a1c6-11eb-8d1b-6c993ce4cdb0.png)
![image](https://user-images.githubusercontent.com/49063068/115330243-3f264000-a1c6-11eb-86a7-5ac4361afce0.png)

**Comment by BeichenDream** [comment]
方便加一下我的微信吗 beichenxp

**Comment by BeichenDream** [comment]
v3.0.1已修复
