### ISSUE TITLE
建议做个程序logo

### ISSUE THREAD

**Issue by z1un** [BeichenDream/Godzilla#3]
建议做个程序logo，哈哈哈

**Comment by solomanhl** [comment]
这是新的聊天方式吗？发自我的华为手机-------- 原始邮件 --------发件人： zjun <notifications@github.com>日期： 2020年8月18日周二 下午3:14收件人： BeichenDream/Godzilla <Godzilla@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [BeichenDream/Godzilla] 建议做个程序logo (#3)

建议做个程序logo，哈哈哈

**Comment by BeichenDream** [comment]
收到

**Comment by webseczone** [comment]
> 收到
你好，我想找你开发一款程序，麻烦你联系我QQ
814069889或者是邮件814069889@qq.com
