### ISSUE TITLE
MacOS下的Bug

### ISSUE THREAD

**Issue by TryHard3r** [BeichenDream/Godzilla#30]
1、MacOS下添加shell默认窗口大小偏小，需要手动调整
![image](https://user-images.githubusercontent.com/24811079/115407301-7f1b1080-a222-11eb-9783-f9d8b31b756c.png)

2、MacOS下添加shell点击测试连接直接卡死，等待几分钟后出现报错信息，版本是最新的3.00
![image](https://user-images.githubusercontent.com/24811079/115407099-57c44380-a222-11eb-9faa-ff22cebf654b.png)

![image](https://user-images.githubusercontent.com/24811079/115407266-7591a880-a222-11eb-8a09-8627263a2b36.png)

**Comment by BeichenDream** [comment]
收到 修改版本解决

**Comment by BeichenDream** [comment]
窗口大小问题已解决  "点击测试连接直接卡死" 设置连接超时为3000即可
