### ISSUE TITLE
3.0.2版本数据库管理失效

### ISSUE THREAD

**Issue by NittaAkio** [BeichenDream/Godzilla#35]
OS：Windows Server 2019 os.version: 10.0 os.arch: amd64
MYSQL：5.7.32-log
JavaDynamicPayload，JAVA_AES_BASE64，UTF-8，NO_PROXY
3.0版本正常连接，3.0.2配置连接信息后提示ok，但无回显

**Comment by BeichenDream** [comment]
已修复 [releases](https://github.com/BeichenDream/Godzilla/releases/tag/v3.03-godzilla)
