### ISSUE TITLE
哥斯拉有很多的问题

### ISSUE THREAD

**Issue by heiyanmaster** [BeichenDream/Godzilla#36]
1.不支持反向代理连接navcat
2.数据库不能保存下来方便下次使用
3.笔记这个玩意儿能不能不进入shell也能看，shell掉了是不是看不了了
4.数据库不支持utf-8的中文输出，只要输出是中文就乱码需要gbk才行，可是这样我的sql语句写中文必定乱码
5.复制文件移动文件这些东西写的好鸡肋啊
6.容易假死，大文件假死？？？建议分线程搞这种事情？？？
阿西吧啊

**Comment by BeichenDream** [comment]
1. 已经在写
2. 暂时不考虑
3. 可以考虑增加
4. 数据库配置那里可以设置数据库字符集
5. 怎么实现比较好？
6. 大文件请用大文件上传/下载

可以添加我微信详聊一下 beichenxp

**Comment by heiyanmaster** [comment]
第四条 数据库乱码问题，我很尴尬说清楚点，就是数据库是utf-8的我设置数据库字符集恩到这里都没问题，但是数据库只要有中文就会乱码 what fuck，但是呢，你要是改成gbk字符集他就好了，无语，还有啊执行数据库命令的时候不能输入中文比如 set username='张三' 这样肯定乱码，还有啊能不能输出数据库dump一下，不然好蛋疼
最后说一下，哥斯拉是不是被阿里狗和腾讯狗盯着呢，上传shell就被抓了，恩....也许需要定制一下不然公开版本还是屠狗

**Comment by heiyanmaster** [comment]
> 1. 已经在写
> 2. 暂时不考虑
> 3. 可以考虑增加
> 4. 数据库配置那里可以设置数据库字符集
> 5. 怎么实现比较好？
> 6. 大文件请用大文件上传/下载
> 
> 可以添加我微信详聊一下 beichenxp

已加
