### ISSUE TITLE
Oracle数据库连接的时候，执行语句提示“ORA-0091：无效字符”

### ISSUE THREAD

**Issue by klmyssn** [BeichenDream/Godzilla#38]
![image](https://user-images.githubusercontent.com/37890522/117661810-6bcfe500-b1d1-11eb-8a27-272f3cbdff23.png)
连接Oracle后随便执行一个默认的语句，提示这个无效字符，后面在作者的指导下发现是因为带了后面的分号";",把结尾的分号去掉就可以了，因此执行语句的时候都要去掉分号就可以正常显示数据了。
非常感谢Beichen师傅开发的这款工具，辛苦啦！！！
![image](https://user-images.githubusercontent.com/37890522/117662103-c49f7d80-b1d1-11eb-8592-a7510047c4cd.png)

**Comment by BeichenDream** [comment]
已修复
