### ISSUE TITLE
请问大佬，数据库连接是不是暂时还不能指定数据库名？

### ISSUE THREAD

**Issue by wangtua** [BeichenDream/Godzilla#39]
如下图，只有用户名和密码，没有数据库名
![image](https://user-images.githubusercontent.com/14075377/118255294-ab9f1100-b4de-11eb-934f-0fbf7550e4a6.png)

**Comment by wangtua** [comment]
再补充一个问题，大文件下载的数据长度是否可以从Java.Integer扩展到Java.Long？

**Comment by BeichenDream** [comment]
> 再补充一个问题，大文件下载的数据长度是否可以从Java.Integer扩展到Java.Long？目前文件下载的大小还是有点不够。

大文件下载是每次下载多少字节而不是一共下载多少字节 现在已更新数据库名
