### ISSUE TITLE
插件从哪里下载啊

### ISSUE THREAD

**Issue by yogistudio** [BeichenDream/Godzilla#4]
没有插件下载位置啊。

**Comment by BeichenDream** [comment]
下个版本更新插件商店

**Comment by whitesharks** [comment]
> 下个版本更新插件商店

牛逼！

**Comment by 1151806933** [comment]
更新了么 
![图片](https://user-images.githubusercontent.com/61936554/114257893-8148c800-99f5-11eb-94b3-ecd3bcd00d46.png)
依然不能安装插件啊
