### ISSUE TITLE
Initialize Fail !

### ISSUE THREAD

**Issue by xiaoyiddos** [BeichenDream/Godzilla#42]
Nginx 1.20 + PHP 7.3.4

本地搭建起来生成php的3种payload都无法
![image](https://user-images.githubusercontent.com/46039468/119530717-db3efa80-bdb5-11eb-865d-4896a12c9db2.png)

添加proxy代理 第二次请求无回显
![image](https://user-images.githubusercontent.com/46039468/119530850-fa3d8c80-bdb5-11eb-8267-3d9953b73a18.png)
![image](https://user-images.githubusercontent.com/46039468/119530871-00336d80-bdb6-11eb-96d5-5e2bf287205a.png)

**Comment by BeichenDream** [comment]
加我微信beichenxp

**Comment by BeichenDream** [comment]
已解决

**Comment by youki992** [comment]
话说我也出现了这样的问题，该怎么解决
