### ISSUE TITLE
initShellOperation Fail

### ISSUE THREAD

**Issue by wintermoon99** [BeichenDream/Godzilla#44]
这个错误是怎么回事啊？

![image](https://user-images.githubusercontent.com/48474591/121135210-da52a200-c866-11eb-9726-5334b360d426.png)

**Comment by wangtua** [comment]
确认上传成功了吗?看看浏览器访问有没有报错，如果浏览器访问没问题的化就是流量被拦截了，不然就是解析错误之类的。

**Comment by wintermoon99** [comment]
可能是拦截了，后续在本地环境测试，是可以的

**Comment by wintermoon99** [comment]
可能是拦截了，后续在本地环境测试，是可以的

**Comment by BeichenDream** [comment]
对于Java遇到这种问题通常是session持久化问题   你只需要在生成的shell把session替换成application即可

对于CSharp遇到这种问题通常是session持久化问题   你只需要在生成的shell把Session替换成Application即可

这种问题将在下一个版本完美修复

**Comment by kalivim** [comment]
> 对于Java遇到这种问题通常是session持久化问题 你只需要在生成的shell把session替换成application即可
> 
> 对于CSharp遇到这种问题通常是session持久化问题 你只需要在生成的shell把Session替换成Application即可
> 
> 这种问题将在下一个版本完美修复

请问，现有版本这个问题如何处理呢？

**Comment by EMU-TIME** [comment]
> 对于Java遇到这种问题通常是session持久化问题 你只需要在生成的shell把session替换成application即可
> 
> 对于CSharp遇到这种问题通常是session持久化问题 你只需要在生成的shell把Session替换成Application即可
> 
> 这种问题将在下一个版本完美修复

关键字“payload”可以改吗？

**Comment by Pacha-kutiq** [comment]
![image](https://user-images.githubusercontent.com/101460915/162930872-5e5e4ca9-2e0d-4a7c-a3f9-2d92c4aab31c.png)
我php的也连不上，生成的时候不加密也连不上，但是浏览器就能打开。下的是最新版，java版本也是够的。楼上有大佬说流量被拦截了，请问怎么解决（访问的是本地的，同样的马蚁剑就连的上），谢谢

**Comment by yang092749** [comment]
我把防火墙关了，还是提示初始化失败
