### ISSUE TITLE
运行后没有工具栏

### ISSUE THREAD

**Issue by tankcaptain** [BeichenDream/Godzilla#48]
java1.8和java16都试了，运行最新版Godzilla之后没有工具栏，只有我一个人有这种问题吗

**Comment by KuaiLeDeXiaoHua-X** [comment]
windows下有工具栏，Mac下无工具栏，大佬们求解决办法

**Comment by guchangan1** [comment]
metoo

**Comment by tankcaptain** [comment]
好tm尴尬，他那个工具栏在系统的工具栏上。。。用了两个月还没习惯。。。。。
