### ISSUE TITLE
为啥JSP和ASP都有AES版本，唯独PHP没有？

### ISSUE THREAD

**Issue by xsshim** [BeichenDream/Godzilla#5]
是不是作者想偷懒？哈哈

**Comment by solomanhl** [comment]
这样说话多累  拉我们进群吧发自我的华为手机-------- 原始邮件 --------发件人： xsshim <notifications@github.com>日期： 2020年8月19日周三 晚上8:48收件人： BeichenDream/Godzilla <Godzilla@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [BeichenDream/Godzilla] 为啥JSP和ASP都有AES版本，唯独PHP没有？ (#5)

是不是作者想偷懒？哈哈
