### ISSUE TITLE
3.03在mac上运行时，添加目标UI显示不完整 13.3英寸(2560 × 1600)

### ISSUE THREAD

**Issue by FlyingPikachus** [BeichenDream/Godzilla#50]
上一个关闭了 重新提交一个
3.03在mac上运行时，添加目标UI显示不完整 
13.3英寸(2560 × 1600)

**Comment by guchangan1** [comment]
同

**Comment by BeichenDream** [comment]
重复文档 https://github.com/BeichenDream/Godzilla/issues/49
