### ISSUE TITLE
带符号的密码或密钥会导致 initshelloperation fail

### ISSUE THREAD

**Issue by dointisme** [BeichenDream/Godzilla#57]
有价值的信息如下
[*] Time:2021-11-25 20:19:27 ThreadId:1 Message: load pluginJar success! pluginJarNum:0 LoadPluginJarSuccessNum:0
[*] Time:2021-11-25 20:19:28 ThreadId:1 Message: load payload success! payloadMaxNum:4 onceLoadPayloadNum:4
[*] Time:2021-11-25 20:19:28 ThreadId:1 Message: load cryption success! cryptionMaxNum:14 onceLoadCryptionNum:14
[*] Time:2021-11-25 20:19:28 ThreadId:1 Message: load plugin success! pluginMaxNum:47 onceLoadPluginNum:47
[!] Time:2021-11-25 20:21:08 ThreadId:19 Message:
[!] Time:2021-11-25 20:21:08 ThreadId:19 Message: payload Initialize Fail !
[!] Time:2021-11-25 20:21:18 ThreadId:19 Message:
[!] Time:2021-11-25 20:21:18 ThreadId:19 Message: payload Initialize Fail !

**Comment by BeichenDream** [comment]
什么类型的有效载荷(webshell)
