### ISSUE TITLE
Filter内存马无法使用

### ISSUE THREAD

**Issue by qiqingshiwo** [BeichenDream/Godzilla#58]
成功打了内存马
![image](https://user-images.githubusercontent.com/33613050/147050078-e0fb5356-0be8-465f-88e3-bb208d5afe77.png)
初始化时失败
![image](https://user-images.githubusercontent.com/33613050/147050192-3b3a3ef6-bd39-456f-8638-d87a4615b509.png)
重复测试多次,发现大部分是空白
![image](https://user-images.githubusercontent.com/33613050/147050599-be25f1a5-178f-4e96-8ff3-4b49f8a9ffc7.png)
少部分返回56字符
![image](https://user-images.githubusercontent.com/33613050/147050705-3c645cbc-892c-4876-9c1d-02677e186fcb.png)
解开这个字符,内容是OutputStream is null

**Comment by BeichenDream** [comment]
这是bug 请使用3.0左右的哥斯拉连接  下个版本更新

**Comment by qiqingshiwo** [comment]
好的,3.0测试可以链接,需要我关闭这个issue吗
