### ISSUE TITLE
中文乱码，建议添加文件上传进度功能

### ISSUE THREAD

**Issue by Yur5n** [BeichenDream/Godzilla#6]
shell访问中文文件夹乱码，建议上传文件加一个上传进度，大文件上传会容易没反应
![1](https://user-images.githubusercontent.com/34226025/90758198-3ae11480-e311-11ea-8797-e6a2c5f13820.png)

**Comment by BeichenDream** [comment]
乱码请在shell设置中选择编码

**Comment by Ac0ne** [comment]
设置选哪个编码才不乱码啊师傅？我改了几个好像不行啊。
