### ISSUE TITLE
jar包无法打开

### ISSUE THREAD

**Issue by Rotund-jere** [BeichenDream/Godzilla#61]
在win10下 有java11和java8两个环境，但是下载jar包后就是空白的，双击后没有显示客户端，就单纯的跳了个cmd界面然后就消失没效果了。。大佬有没有解决办法呢。

**Comment by BeichenDream** [comment]
用控制台启动看看呢 java -jar Godzilla.jar

**Comment by Rotund-jere** [comment]
尝试过了，可能是我双环境变量在win下搞得不好。卸载后，单独安了个11就好用，再按个8还没有尝试。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BeichenDream/Godzilla"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月13日(星期天) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BeichenDream/Godzilla] jar包无法打开 (Issue #61)





 
用控制台启动看看呢 java -jar Godzilla.jar
