### ISSUE TITLE
一个小bug

### ISSUE THREAD

**Issue by broeeee** [BeichenDream/Godzilla#62]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by core.EasyI18N (file:/usr/share/godzilla/godzilla.jar) to field javax.swing.JTable.uiClassID
WARNING: Please consider reporting this to the maintainers of core.EasyI18N
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
An illegal reflective access operation has occurred

![image](https://user-images.githubusercontent.com/18160411/155642416-9aae8eb3-16cb-40c4-aa82-31c91cc46d2c.png)

java版本
└─# java -version         
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1, mixed mode, sharing)

└─# uname -a                         
Linux kali 5.15.0-kali2-amd64 #1 SMP Debian 5.15.5-2kali2 (2021-12-22) x86_64 GNU/Linux

不是听说有机会合并哥斯拉和冰蝎么。又没计划啊。

**Comment by BeichenDream** [comment]
> WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by core.EasyI18N (file:/usr/share/godzilla/godzilla.jar) to field javax.swing.JTable.uiClassID WARNING: Please consider reporting this to the maintainers of core.EasyI18N WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release An illegal reflective access operation has occurred
> 
> ![image](https://user-images.githubusercontent.com/18160411/155642416-9aae8eb3-16cb-40c4-aa82-31c91cc46d2c.png)
> 
> java版本 └─# java -version openjdk version "11.0.14" 2022-01-18 OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1) OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1, mixed mode, sharing)
> 
> └─# uname -a Linux kali 5.15.0-kali2-amd64 #1 SMP Debian 5.15.5-2kali2 (2021-12-22) x86_64 GNU/Linux
> 
> 不是听说有机会合并哥斯拉和冰蝎么。又没计划啊。

不影响正常使用 爆这个异常是尝试动态注入I18N国际化的时候遍历到了JDK内部类
