### ISSUE TITLE
asp shell 设置 HTTP 代理初始化失败

### ISSUE THREAD

**Issue by Go0p** [BeichenDream/Godzilla#68]
设置 http 代理

![image](https://user-images.githubusercontent.com/38928800/175847015-84bf947a-1d20-4f08-beb2-6a8c10c3df9d.png)

取消设置

![image](https://user-images.githubusercontent.com/38928800/175847227-bf93526a-cad0-41bb-b95b-d170ba44776a.png)

**Comment by BeichenDream** [comment]
Wireshark抓包看看 或者换成XOR_BASE64加密器

**Comment by Go0p** [comment]
好像不是哥斯拉的问题，好像是 mitmproxy 的问题，使用 burp 连接正常
