### ISSUE TITLE
t00ls专用版和普通版有啥区别？

### ISSUE THREAD

**Issue by vtunnel** [BeichenDream/Godzilla#7]
大佬，t00ls专用版和普通版有啥区别？

Godzilla.jar
Godzilla-t00ls.jar

这俩打开看着是一样的？

**Comment by Mr-xn** [comment]
> 大佬，t00ls专用版和普通版有啥区别？
> 
> Godzilla.jar
> Godzilla-t00ls.jar
> 
> 这俩打开看着是一样的？

😄 标题不一样
