### ISSUE TITLE
大文件上传功能问题

### ISSUE THREAD

**Issue by lif3reb00t** [BeichenDream/Godzilla#72]
貌似文件每次只截取1MB大小内容传输给服务端，最终的文件内容基本都是那1MB的，而且会多传输一次造成原文件大小与传输后文件大小不同。

![image](https://user-images.githubusercontent.com/37888957/178959350-eb564c2c-173a-4e16-9ffe-04ae1c35ec78.png)

![image](https://user-images.githubusercontent.com/37888957/178959560-d1eaa08f-6419-4665-a84d-b90d2da7b222.png)

**Comment by lif3reb00t** [comment]
测试的是Spring boot gateway的Spel注入环境

**Comment by BeichenDream** [comment]
文件能发我一下吗

**Comment by BeichenDream** [comment]
> 测试的是Spring boot gateway的Spel注入环境


文件能发我一下吗？上传的结束之前有什么提示框弹出吗？

**Comment by lif3reb00t** [comment]
刚才又测试了下正常环境，没有像Spring boot gateway的那种情况，很尬。师傅可以尝试在本地去传到Spring boot gateway的环境上，因为它会有个256KB限制，如果打内存马进去要传大点的文件就没办法搞。

**Comment by BeichenDream** [comment]
> 刚才又测试了下正常环境，没有像Spring boot gateway的那种情况，很尬。师傅可以尝试在本地去传到Spring boot gateway的环境上，因为它会有个256KB限制，如果打内存马进去要传大点的文件就没办法搞。

配置里面有一个大文件上传，你把单次上传大小改小点比如50k或者100k
![image](https://user-images.githubusercontent.com/43266206/178961533-d40a5002-2440-4317-801a-db8e0ffc28d1.png)

**Comment by lif3reb00t** [comment]
> > 刚才又测试了下正常环境，没有像Spring boot gateway的那种情况，很尬。师傅可以尝试在本地去传到Spring boot gateway的环境上，因为它会有个256KB限制，如果打内存马进去要传大点的文件就没办法搞。
> 
> 配置里面有一个大文件上传，你把单次上传大小改小点比如50k或者100k ![image](https://user-images.githubusercontent.com/43266206/178961533-d40a5002-2440-4317-801a-db8e0ffc28d1.png)

好的，谢谢师傅。我这就过去看下

**Comment by lif3reb00t** [comment]
感谢师傅，这个程序配置，之前没用过。还以为没办法改文件上传的大小。已解决！
