### ISSUE TITLE
asmx本地测试链接失败

### ISSUE THREAD

**Issue by qiqingshiwo** [BeichenDream/Godzilla#73]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/33613050/179659886-314ad183-e687-49ca-8d77-6bbd18365ebf.png">
操作系统是windows 2008 32,默认安装的IIS 7.0,开启了支持asp.net的功能,然后,使用默认生成的哥斯拉asmx,访问一切正常,链接直接GG

**Comment by BeichenDream** [comment]
生成和连接的时候选择asmx加密器，不要选aes_base64

**Comment by qiqingshiwo** [comment]
正常了,感谢作者
