### ISSUE TITLE
插件问题

### ISSUE THREAD

**Issue by sorefw** [BeichenDream/Godzilla#82]
内置插件没有几个，自己加载的插件也不能显示

**Comment by BeichenDream** [comment]
插件分为后渗透插件和工具插件。

目前开放的插件都是后渗透插件，需要进入shell才能看到，而主页面的插件是工具插件。
![image](https://user-images.githubusercontent.com/43266206/204074883-3e0a9060-4f9e-409c-ae71-6a90dc367e93.png)
